name: Cross Compile Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain and cross
        run: |
          rustup target add ${{ matrix.target }}
          cargo install cross

      - name: Cross-compile with cross
        run: cross build --target ${{ matrix.target }} --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linht-gui-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/
            flowgraph/
            fonts/

